from typing import Dict, Any, List

from pydantic import BaseModel, Field

from app.schemas.workflow import Workflow

class WorkflowRunRequest(BaseModel):
    """Payload to trigger a workflow run."""
    workflow: Workflow = Field(..., description="The workflow graph to execute.")

class NodeExecutionResult(BaseModel):
    """Result of a single node's execution."""
    node_id: str
    output: Any = Field(..., description="The structured output generated by the node.")
    duration_ms: float = Field(..., description="Execution duration in milliseconds.")
    error: str | None = Field(None, description="Error message if execution failed.")

class WorkflowRunResponse(BaseModel):
    """The final response sent back after a workflow run finishes."""
    status: str = Field(..., description="'success' or 'error'")
    total_duration_ms: float
    results: List[NodeExecutionResult] = Field(default_factory=list, description="Per-node execution results.")
    final_output: Any | None = Field(None, description="The aggregated final output of the workflow.")

class WorkflowValidationError(BaseModel):
    """Detailed error representing validation failures in the workflow format."""
    message: str
    code: str
